---
- name: be sure ntp is installed
  yum:
    name: chrony
    state: present
  tags: ntp
- name: be sure ntp is configured
  template:
    src: {{ ntp-src_file }}
    dest: {{ ntp-dest_file }}
  notify:
    - restart ntpd
  tags: ntp
- name: be sure ntpd is running and enabled
  service:
    name: chronyd
    state: started
    enabled: yes
  tags: ntp
- name: Set Timezone
  community.general.timezone:
   name: {{ time_zone_location }}
   
